### ISSUE TITLE
Object Outline Bug (fix included)

### ISSUE THREAD

**Issue by psc-87** [napalm00/PlaceInRedStandalone#1]
Hey! I fixed a bug with the "Disable Object Outlines" where the last object's outlined would show up on the user's screen if they hovered over an NPC (when outlines should be disabled completely).  See screenshot at the bottom for an example.

I think this happens because the workshop input layer handles npcs differently than standard objects.  The fix is pretty simple - changing 1 byte near the same memory pattern to create an unconditional jump . I tested this fix in the cheat table version (for both FO4 and FO4VR) and it seems to work well:
https://github.com/napalm00/PlaceInRedStandalone/blob/6ac9652dc66d45ace1aab9b29f9852b706ff76ca/PlaceInRedStandalone/PlaceInRedStandalone.h#L156
Add new line:
```
MemoryUtils::PatchMemory(m_PointersMap["_aob_outlines"].address + 0x0D, {0x76});
```
https://github.com/napalm00/PlaceInRedStandalone/blob/6ac9652dc66d45ace1aab9b29f9852b706ff76ca/PlaceInRedStandalone/PlaceInRedStandalone.h#L161
Add new line:
```
MemoryUtils::PatchMemory(m_PointersMap["_aob_outlines"].address + 0x0D, {0xEB});
```

Pretty minor bug... but definitely annoying if you do encounter it. Let me know your thoughts!

![bug](https://user-images.githubusercontent.com/11322186/34661453-1514c86a-f407-11e7-9259-467095ce38d4.png)

**Comment by napalm00** [comment]
Fixed in [43aa397](https://github.com/napalm00/PlaceInRedStandalone/commit/43aa397faa2c1d23dc61f94209f69dcb5288eab5) and released in [1.1](https://github.com/napalm00/PlaceInRedStandalone/releases/tag/1.1). Thank you!
