### ISSUE TITLE
Plugin Crash Beta 1.1.24

### ISSUE THREAD

**Issue by eldarstorm** [napalm00/PlaceInRedStandalone#2]
Plugin Crashes after game loads
"Error: _aob_groundsnap is NULL. This probably means the mod is outdated."

Running Fallout4 VR Beta 1.1.24.0
![place_in_red_1 0_error](https://user-images.githubusercontent.com/1494001/35765386-33dcf76e-0888-11e8-8294-3ff5b01d60b0.jpg)

**Comment by napalm00** [comment]
Fixed in 5021ee6, version 1.2 released. Thanks!
