### ISSUE TITLE
Crashes the game, incompatible with recent patch?

### ISSUE THREAD

**Issue by joycourier** [napalm00/PlaceInRedStandalone#3]
Hello! 

Although this mod _does_ work, there are many people reporting crashes when using the mod. Seemingly related to Dogmeat, but mostly just spontaneous.

I would understand you having no personal interest in the game or the mod anymore, but would you accept a donation in exchange for taking a look at the mod and resolving the crashes? I would happily pay any fee as it seems many people are sorely missing this mod, myself included.

**Comment by napalm00** [comment]
Hey, 
I've looked at the mod and updated a few things. I've tried meeting with Dogmeat and playing around a bit and it doesn't seem to crash anymore.
I'll attach the updated version, let me know if it fixes the crashes for you so I can proceed and push this to the repo & Nexus.


[steam_api64.zip](https://github.com/napalm00/PlaceInRedStandalone/files/3506918/steam_api64.zip)

**Comment by joycourier** [comment]
I really appreciate that, thank you. It hasn't crashed for me after a good few minutes of dicking around so that's great. 

The terminal settings holotape acts a little strange when you re-load a save but it's nothing major. Can go into detail if you would like.

[Edit: and my Fallout4Prefs was reset to default after changing my steamapi.dlls, not sure if that was actually your mod or not.]

Also, when combined with Scrap Everything, I can move items that I was previously unable to, like the entire Red Rocket building. With only SE I could only scrap these items, not move them. That's an awesome feature, even if unintended.

You've got no donate button I can see anywhere but I'm happy to pay for the work, one CompSci student to another. F4SEVR just came out so I expect FO4VR will see a bit more life soon, I bet hundreds if not thousands will be grateful that your mod's alive again.

**Comment by napalm00** [comment]
Good to know it appears to be fixed! I'm actually curious what the settings holotape does when reloading a save, so if you could provide more insight that'd be great.

The mod doesn't touch Fallout4Prefs so I'm not sure why it was reset, same with being able to move all items, I suppose it's some side effect of removing building limits.

My PayPal link is https://paypal.me/napalm00, I didn't initially plan on it but I'll happily accept any donation!

**Comment by joycourier** [comment]
So about the terminal, after reloading a save it wasn't showing the value of the booleans correctly. For example; the first setting was '0.00' but Place In Red was still working, or Disable Ground Snap was set to '0.00' but I could stick a chair in the floor.

At some point it wasn't actually changing anything when I tried to change the settings in the terminal, but after reloading _again_ it actually changed stuff, but still didn't update the terminal's values.

That's why I said it's nothing major, a little finicky but heck it, the mod works and I'm a happy man. Remember to make a post on r/fo4vr about updating your mod, that's gonna get so many updoots. At least 5.

**Comment by napalm00** [comment]
I can't get the terminal to work properly either, Bethesda must've changed something in how the variables are set.

Oh well, it isn't a vital feature so I'll just update the mod as-is. Thank you for your support!
